### PR TITLE
Added Intel compiler to CPU Makefiles (And .gitignore)

### PR DESCRIPTION
**Pull request by ZuluPro**
This does not change the previous behavior. If a user does only `make`, it'll use `g++`.
But user can now do `make icpc`.

Maybe you want me to add this to another makefiles ?
Or docs later.

### CODE REVIEW

**Comment by ZuluPro** [comment]
@tristanvdb @cavazos 
Any news ?

**Comment by ZuluPro** [comment]
@tristanvdb @cavazos Any news ? Something wrong on my code ?

**Comment by ZuluPro** [comment]
@tristanvdb @cavazos Any news ?

**Comment by ZuluPro** [comment]
@tristanvdb @cavazos Any news ?

**Comment by ZuluPro** [comment]
Still no news...............

**Comment by VincentSC** [comment]
We've asked to take over the project, so the code could be tuned and optimized for new and recent architectures. We're waiting for an email response. The unaltered fork is currently at https://github.com/StreamHPC/FinanceBench

Your MR could better use the CXX variable to make it more generic. Then add parameter `-xHost` only for `icpc`. Then it would use the default compiler, unless overridden.
Project can better be ported to cmake to make it more flexible, including using another compiler than gcc, including clang.

**Comment by willkill07** [comment]
@ZuluPro We encourage others to now use the (approved) StreamHPC fork of FinanceBench.

@VincentSC I visited your fork recently. It may make sense to have `develop` be the default branch instead of `master` so folks grab the latest + greatest from your new contributions.

I will be archiving this repository and updating the README / description to refer to StreamHPC's fork.

**Pull request closed without merging**
